### ISSUE TITLE
How do you build and version your documentation?

### ISSUE THREAD

**Issue by jseldess** [coreos/docs#1082]
I'm one of the writers of the [CockroachDB docs](https://github.com/cockroachdb/docs). We're planning how to best version our documentation, and your site is one we're looking to for inspiration. But in your repo, I can't find any indication of how you build and version your site. Would you be willing to share your approach?

**Comment by robszumski** [comment]
Hi @jseldess, here's how it works:

On each release, we "sync" the docs from various sources into a private repo which holds our website. We maintain some private metadata that contains categories, the version, the project name, and a customized title that can be different from the title contained in the content. Our listing pages loop over these categories and versions to construct the page.

The sources of these files are typically layered from a few different repos:
 - source of github.com/fooproject/Documentation at git tag v.x.x.x
 - source of github.com/coreos/barproject at git master
 - source of github.com/coreos/docs/fooproject at git master

Why do this? The main source of docs needs to be versioned with what is in the actual project release. This is something like etcd v1.2.3. This version number ends up in the metadata. The other 1 or 2 repos are typically docs from relevant repos that intersect, but the versioning isn't as hard of a requirement. Lastly, the docs in this repo are also synced from master. These are here because they pertain to things we want to document, but might not be applicable to the upstream project as a whole. For example, guides for using etcd _on Container Linux_, where the upstream project doesn't want to express an OS in a more favorable light. This is the right thing to do for the OSS community, but makes it harder on our release process.

**Comment by jseldess** [comment]
Thanks for the thorough explanation, @robszumski! Your setup is significantly more complex than ours, with multiple projects and dependencies. But it's very useful to hear how you handle it. 

cc: @mjibson and @benesch
