### ISSUE TITLE
coreos + criu

### ISSUE THREAD

**Issue by giper45** [coreos/docs#1128]
I'd like to use criu inside coreos. I'm able to install criu with toolbox but I'm not able to use it with docker (out of the "toolbox container"). I tried to copy criu from /bin/ (in toolbox) to  /media/root/opt/bin  (that is /opt/bin in coreos context), and the command seems to work:

<img width="591" alt="schermata 2017-07-31 alle 13 25 18" src="https://user-images.githubusercontent.com/18548727/28775714-bcee0bce-75f3-11e7-8aac-e9f863498cf0.png">

But when I try to use it with docker it gives the following error: 

```
core@localhost ~ $ docker run -d --name looper --security-opt seccomp:unconfined busybox  \
>          /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
0e5f89575e5467133b607920def05b3b7b3c2c367ccbd360ae220d52478c1a13
core@localhost ~ $ docker logs looper
0
1
2
3
4
5
core@localhost ~ $ docker checkpoint create looper checkpoint1
Error response from daemon: Cannot checkpoint container looper: rpc error: code = 2 desc = exit status 1: "Unable to execute CRIU command: criu\n"
core@localhost ~ $ 

```

I've seen that criu is integrated on coreos-overlay but I don't know how it works:
https://github.com/coreos/coreos-overlay
I should create a custom coreos image with criu installed ? How I can do this ? With sdk ? Is there any guide to do something like this? 
Thanks in advance!

**Comment by euank** [comment]
While you can build custom image ([docs](https://coreos.com/os/docs/latest/sdk-modifying-coreos.html)), we don't recommend doing it generally since it prevents automatic updates.

The reason `docker` is complaining about being unable to find `criu` is presumably that it's not in `dockerd`'s path. Since `dockerd` is started by systemd, using `systemctl set-environment PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin` will likely allow `docker` to find it (note, the current value for PATH can be found with `systemctl show-environment`).

Regardless, the proper fix is for us to include the criu binary appropriately to fix this.
Would you be willing to file this as a feature request against https://github.com/coreos/bugs?
If you'd like, you could have a shot at updating the torcx package (via https://github.com/coreos/coreos-overlay/blob/master/app-torcx/docker/docker-17.05.ebuild) to include criu.

**Comment by euank** [comment]
(closing since I think this is a bug/feature-request, not a documentation issue)

**Comment by giper45** [comment]
Thanks to @euank, you saved my life! I've set system environment path with criu directory and It perfectly works, docker see it! Now I try to send the request to bugs section, so they could integrate criu in next coreos versions.
Thanks very much!
