### ISSUE TITLE
Documentation for cluster recovery for etcd2

### ISSUE THREAD

**Issue by marcovc** [coreos/docs#1139]
Hi,

I'm using coreos stable channel. The documentation for recovering failed nodes for my system appears to have suddenly disappeared from the internet. The new documentation doesn't apply to my system (the /etc/systemd/system/etcd-member.service.d directory doesn't even exist).

After some research I found it in an old revision here:
https://github.com/coreos/docs/blob/fc211d51ec7ae0d4366514828baf25e66c9490d3/etcd/etcd-live-cluster-reconfiguration.md

What is going on? If there was some manual update of some component (I'm thinking etcd3?)  that I should have done, then can you please keep the old documentation somewhere?

Thanks!
Marco

**Comment by euank** [comment]
There are a couple different questions, so I tried to split my answer to cover them

### Doc versioning / old versions

So first of all, yes we do trim older versions of some documentation. It varies by project how many versions are kept. etcd keeps all versions I think. Container Linux keeps the last 5 per channel.

Since those are etcd docs, the old version should be there. It can be found with the dropdown on the upper-left for "version" and picking the appropriate one, giving a URL like https://coreos.com/etcd/docs/2.3.7/etcd-live-cluster-reconfiguration.html

The reason those versions of the docs aren't shown prominently, though, is that it's recommended you use the etcd v3 daemon instead of the v2 one.

### etcd2 -> 3 transition

The docs likely do apply to your system if you migrate to etcd3, which is recommended. The path `/etc/systemd/system/etcd-member.service.d` not existing is expected; you can check if you have the `etcd-member` unit with something like `systemctl status etcd-member.service`. All channels have had it for a while.

For backwards compatibility, we've had to leave the `/usr/bin/etcd2` binary in place, but we recommend people switch to the etcd-member.service, which runs etcd3 in a container for you.

etcd has [some documentation](https://coreos.com/etcd/docs/latest/upgrades/upgrade_3_0.html) on this migration and on running it on [Container Linux](https://coreos.com/etcd/docs/latest/getting-started-with-etcd.html).


Hopefully that answered your question; if not let me know

**Comment by marcovc** [comment]
Ooops, sorry, I didn't notice the version dropdown.

Thanks for your help euank.
