### ISSUE TITLE
'Customizing the SSH daemon' doc doesn't show how to modify sshd_config params after first boot

### ISSUE THREAD

**Issue by sdanieru** [coreos/docs#1215]
This document page:
https://coreos.com/os/docs/latest/customizing-sshd.html
Demonstrates how to define sshd_config parameters, change service port, etc. with a Container Linux Config.

In the 'Customizing sshd after first boot' it then says:

"The following sections walk through applying the same changes documented above on a running machine."

Yet, it doesn't explain how to define sshd_config parameters, only how to specify which IP:port to bind the ssh service to. Can steps be added to the documentation?

**Comment by euank** [comment]
Yes, it's possible. Since the `sshd_config` file is a symlink, it first has to be replaced with an actual file (e.g. via `sudo sed -i '' /etc/ssh/sshd_config`), and then it can be edited and reloaded (`systemctl reload sshd`) per normal.

Good catch that the docs miss mentioning this! Feel free to have a shot at fixing it if you have the time/desire, otherwise I can update them once I have spare cycles.
