### ISSUE TITLE
None human readable config files

### ISSUE THREAD

**Issue by mxb78** [coreos/docs#1279]
Hey (wave),
new to CoreOS and pxe install.
I think to use JSON for config is a big mistake. 
"ct" should interpret human (yaml) written config during install into JSON out-of-the box.
I think, I should not struggle with this at all , by downloading "ct" in order to convert.
Why to "re-invent the wheel" ??
This should be SIMPLE to a HUMAN.
Sure I can dig around and solve this, but this costs TIME.

Please convert HUMAN to JSON with help of machine, Out of the box.

**Comment by bgilbert** [comment]
If I'm understanding correctly, you'd like Container Linux Configs to be interpreted by Container Linux directly, rather than requiring them to be processed by CT first.

Part of the goal of CT is to catch common config errors before the config is passed to a machine.  The separate transpilation step allows this.  Otherwise, all debugging would have to happen directly on the machine, which can be inconvenient.

Container Linux is currently in maintenance mode and is not receiving large changes.  We're working on [Fedora CoreOS](https://getfedora.org/coreos/), the successor to Container Linux.  Fedora CoreOS currently also separates the transpilation and provisioning steps, though we've discussed possibly integrating the config transpiler into the distro in the future.
