### ISSUE TITLE
Rackspace provisioning guide is borked

### ISSUE THREAD

**Issue by iangcarroll** [coreos/docs#742]
https://coreos.com/os/docs/latest/booting-on-rackspace.html

Looks like a div didn't get closed, as the rest of the page is under the "Alpha" tab.

**Comment by robszumski** [comment]
This was caused by a switch to the markdown renderer for coreos.com. Thanks for reporting, we're looking into it.

For anyone interested, we're using Jekyll 3 and were encouraged by Github's switch to Kramdown (we're using rdiscount currently). It has trouble rendering mixed HTML and markdown. This is part of the markdown "spec", however.

**Comment by crawford** [comment]
@robszumski that page has unclosed anchor tags.
