### ISSUE TITLE
tty0 Default console login user 

### ISSUE THREAD

**Issue by lgreenlee** [coreos/docs#763]
A user with a password should be configured by default without the need for a cloud-config for applications where a tty is available. For example, XenServer allows console access. 

Relying on the network and the user to supply a perfect cloud-config is unrealistic and can result in an image becoming unusable due to a simple error in the cloud-config. The recovery options in this case are time consuming. 

It is possible to exclude a user from ssh and restrict their access to the tty.

**Comment by crawford** [comment]
If you have access to the tty, use the `coreos.autologin` kernel command line argument to get access to the machine.

**Comment by lgreenlee** [comment]
Thanks, I saw the docs on this. I get the secure by default, supply the keys stance. This is almost the other extreme - leave the door open. We just need a normal login, like a "normal" system that is still moderately secure but not accessible from the outside.

**Comment by crawford** [comment]
You can use `coreos.autologin=ttyS0` to limit it to particular console, but either way, the machine should be rebooted after you are done provisioning with this flag (otherwise, the serial console remains open). This is mostly useful for debugging - I don't know of any production systems using this regularly.

Ignition or cloud-init are the better tools for setting up a system. https://coreos.com/validate/ can help validate cloud-configs (Ignition support will be added eventually).

**Comment by lgreenlee** [comment]
Ok, thank you!
