### ISSUE TITLE
Software RAID on Hetzner

### ISSUE THREAD

**Issue by vmatekole** [coreos/docs#790]
Hi!

I would like to run CoreOS on SW RAID on bare-metal on Hetzner but cannot find any consistent documentation. Will this be addressed anytime soon?

**Comment by robszumski** [comment]
The Hetzner part or the software raid part?

For raid, check out this Ignition example: https://coreos.com/ignition/docs/latest/examples.html#create-a-raid-enabled-data-volume

Ignition is needed for this because it runs before systemd even boots, which means your disks get formatted as early as possible in the boot process. You can pass this Ignition config to the CoreOS install script.

**Comment by robszumski** [comment]
Closing in favor of https://github.com/coreos/bugs/issues/1232

**Comment by vmatekole** [comment]
Hi! @robszumski  thanks for getting back, appreciated. The Hetzner part is taken care of.... This is great! But would this work on the boot drive /dev/sda using RAID1?

**Comment by crawford** [comment]
@vmatekole it doesn't make a whole lot of sense to mirror the USR partitions, so I wouldn't put the boot drive on a RAID array. You could try putting the root partition behind RAID using Ignition. This is not something I have tried and it would be interesting to see the result.

**Comment by vmatekole** [comment]
@crawford Thanks for your input. Ok, that suggests most people are running the root partition on a single drive? Which would mean I would have to have more redundancy in terms of nodes and making sure my apps/dbs can failover gracefully to other nodes in case of HD failure... Which should be the case.... But from my superficial knowledge, having root on a single drive appears quite fragile and pot. for increased failures which you wouldn't have otherwise. E.g. What happens to my Postgres DB, even though it is on a RAID'ed volume, if there is failure on the CoreOS drive, maybe pot. for corruption?
