### ISSUE TITLE
Vultr instructions are broken.

### ISSUE THREAD

**Issue by ryneeverett** [coreos/docs#871]
I can't get the vultr docs to work any more. I last used them about 6 months ago but now when I follow them I can't ssh in (prompts for a password rather than rsa passphrase) nor get any debug info from vultr.

I tried submitting a vultr support ticket but they weren't interested in supporting third-party documentation.

Unless I'm making an error or somebody else knows how to fix the instructions I'd recommend just dropping them.

**Comment by ryneeverett** [comment]
@mwbrown I noticed you recently mentioned using vultr in coreos/bugs#338. Am I crazy here or are you using a different method than described here?

**Comment by mwbrown** [comment]
VULTR allows deploying CoreOS directly as one of their available OS images
when provisioning a new server. All I had to do to get it to work was set
up an SSH key on the account and set that as the authorized key when
creating the server, as opposed to using iPXE.

**Comment by ryneeverett** [comment]
Thanks @mwbrown, that's kind of a relief. But you stated there:

> The trick is to use systemctl enable iptables-restore.service instead of putting it in cloud-config.yml (at least for VULTR hosts).

How do you use a cloud-config.yml without iPXE?

**Comment by mwbrown** [comment]
The way VULTR creates their images is by running cloud-init at every boot
using /usr/share/oem/cloud-config.yml. It has some important VULTR specific
services like setting up SSH keys and what not, but it's persistent across
reboots for things that would normally not not be. However I've found that
using /etc to control most of the configuration was more helpful on those
hosts, because of the fact that they run cloud-init after several other
unit files have already started up.

**Comment by ryneeverett** [comment]
I see. Thanks for putting up with my unsolicited interrogation @mwbrown!

**Comment by ElijahCaine** [comment]
In an effort to triage the docs this is being closed due to inactivity.
